name: Multiple
run-name: Multiple_${{inputs.guid}}
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your name'
        required: true
      age:
        description: 'Enter your age'
        required: true
      guid:
        type: string
        default: "N/A"

jobs:
  multiple-inputs-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Age: ${{ github.event.inputs.age }}"
  multiple-inputs-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Age: ${{ github.event.inputs.age }}"
  
