name: Simple
run-name: Simple_${{inputs.guid}}
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Enter a message'
        required: true
      guid:
        type: string
        default: "N/A"
jobs:
  simple-input-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message
        run: echo "${{ github.event.inputs.message }}"
  simple-input-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Display Message
        run: echo "${{ github.event.inputs.message }}"
